# Navigation Links
# The weight parameter defines the order that links appear in the navbar.

main:
  - name: Home
    url: /
    weight: 10

  - name: Research
    url: research/
    weight: 20

  - name: Projects
    url: projects/
    weight: 30

  - name: Team
    url: team/
    weight: 40

  - name: Join Us
    url: join/
    weight: 50